package(default_visibility = ["//visibility:public"])

cc_library(
  name = "greeter_client",
  hdrs = [
    "greeter_client.h",
  ],
  deps = [
    "//proto:helloworld",
    "//external:grpc",
  ],
  linkstatic = True,
)
